### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marknoack**
I made various copyedits to this section for clarity. 

I also added several tables to organize the fields needed for different steps.

### CODE REVIEW

**Review by swanderz — CHANGES_REQUESTED** [review]
@marknoack you're a maverick -- thanks! My only request is to follow the convention of adding an entry to the `CHANGELOG.md` so we can include your contribution in the notes for the next release! you can make the next version heading `0.21.3` or just `vnext`.

**Comment by marknoack** [comment]
Sorry about that! I'll add the entry to the changelog

**Comment by swanderz** [comment]
> Sorry about that! I'll add the entry to the changelog

no worries! def not your fault for not doing something you weren't asked to do. I should add a checklist to the pull request template....

**Review by swanderz — APPROVED** [review]
approved! thanks @marknoack

**Pull request merged**
